// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// r_to_eigen
Eigen::MatrixXd r_to_eigen(const Eigen::MatrixXd& mat);
RcppExport SEXP _TLPR_r_to_eigen(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(r_to_eigen(mat));
    return rcpp_result_gen;
END_RCPP
}
// processListSEXP
void processListSEXP(SEXP list_sexp, bool is_map, const std::string KeyTypeArg);
RcppExport SEXP _TLPR_processListSEXP(SEXP list_sexpSEXP, SEXP is_mapSEXP, SEXP KeyTypeArgSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type list_sexp(list_sexpSEXP);
    Rcpp::traits::input_parameter< bool >::type is_map(is_mapSEXP);
    Rcpp::traits::input_parameter< const std::string >::type KeyTypeArg(KeyTypeArgSEXP);
    processListSEXP(list_sexp, is_map, KeyTypeArg);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TLPR_r_to_eigen", (DL_FUNC) &_TLPR_r_to_eigen, 1},
    {"_TLPR_processListSEXP", (DL_FUNC) &_TLPR_processListSEXP, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TLPR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
