# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_to_eigen <- function(mat) {
    .Call('_TLPR_r_to_eigen', PACKAGE = 'TLPR', mat)
}

processListSEXP <- function(list_sexp, is_map, KeyTypeArg) {
    invisible(.Call('_TLPR_processListSEXP', PACKAGE = 'TLPR', list_sexp, is_map, KeyTypeArg))
}

CartesianProductRcpp <- function(vectors) {
    .Call('_TLPR_CartesianProductRcpp', PACKAGE = 'TLPR', vectors)
}

CartesianProductRcppParallel <- function(vectors, numThreads) {
    .Call('_TLPR_CartesianProductRcppParallel', PACKAGE = 'TLPR', vectors, numThreads)
}

CartesianProductRcppParallelxLB <- function(vectors, numThreads) {
    .Call('_TLPR_CartesianProductRcppParallelxLB', PACKAGE = 'TLPR', vectors, numThreads)
}

